resources:
- name: ng-concource-ci
  type: git
  source:
    uri: https://github.com/do-mas/ng-concource-ci
    branch: master

- name: staging-app
  type: cf
  source:
    api: https://api.sys01.cf.nl.eu.abnamro.com
    username: siju.mathew
    password: Password2018
    organization: rpb-products-org
    space: 04-development
    random-route: true

jobs:

- name: test-app
  plan:
  - get: ng-concource-ci
    trigger: true
  - task: test
    file: ng-concource-ci/ci/tasks/build.yml
  - put: staging-app
    params:
      manifest: build-out/manifest.yml
      path: build-out/root
